name: MultiWorldMoney
main: com.wasteofplastic.multiworldmoney.MultiWorldMoney
version: 1.7.4
depend: [Vault]
softdepend: [Multiverse-Core]
commands:
   balance:
      description: This tells you how much money you have across all worlds.
      usage: /<command> [player]
      permission: mwm.balance
      permission-message: You don't have <permission>
   mwm:
      description: MultiWorldMoney command
      usage: /<command>
permissions:
   mwm.balance:
      description: Gives access to the balance command
      default: true
   mwm.reload:
      description: Reloads the groups.yml file
      default: op
   mwm.pay:
      description: Allows use of the mwm pay command across worlds
      default: op
      
